apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  namespace: elastic-system
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/simple-webapp-deployment*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-es-http
        Port 443
        HTTP_User elastic
        HTTP_Passwd m7Xu34qrFEGq4119FMWs377y
        Logstash_Format On
        Retry_Limit False
        Suppress_Type_Name On
        tls On  # Enable TLS for HTTPS
        tls.verify Off  # Disable certificate verification if you are using self-signed certs or need to skip validation

    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-es-http
        Port 443
        HTTP_User elastic
        HTTP_Passwd m7Xu34qrFEGq4119FMWs377y
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Suppress_Type_Name On
        tls On  # Enable TLS for HTTPS
        tls.verify Off  # Disable certificate verification if you are using self-signed certs or need to skip validation
