helm repo add elastic https://helm.elastic.co
helm repo update
helm install elastic-operator elastic/eck-operator --namespace elastic-system --create-namespace


bharathkumardasaraju@install-local-k8s-cluster$ helm search repo elastic/eck-operator --versions

NAME                     	CHART VERSION	APP VERSION	DESCRIPTION
elastic/eck-operator     	2.14.0       	2.14.0     	Elastic Cloud on Kubernetes (ECK) operator
elastic/eck-operator     	2.13.0       	2.13.0     	Elastic Cloud on Kubernetes (ECK) operator
elastic/eck-operator     	2.12.1       	2.12.1     	Elastic Cloud on Kubernetes (ECK) operator
elastic/eck-operator     	2.12.0       	2.12.0     	Elastic Cloud on Kubernetes (ECK) operator
elastic/eck-operator     	2.11.1       	2.11.1     	Elastic Cloud on Kubernetes (ECK) operator
elastic/eck-operator     	2.11.0       	2.11.0     	Elastic Cloud on Kubernetes (ECK) operator
elastic/eck-operator     	2.10.0       	2.10.0     	Elastic Cloud on Kubernetes (ECK) operator
elastic/eck-operator     	2.9.0        	2.9.0      	Elastic Cloud on Kubernetes (ECK) operator
elastic/eck-operator     	2.8.0        	2.8.0      	Elastic Cloud on Kubernetes (ECK) operator
elastic/eck-operator     	2.7.0        	2.7.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	2.6.1        	2.6.1      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	2.6.0        	2.6.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	2.5.0        	2.5.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	2.4.0        	2.4.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	2.3.0        	2.3.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	2.2.0        	2.2.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	2.1.0        	2.1.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	2.0.0        	2.0.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.9.1        	1.9.1      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.9.0        	1.9.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.8.0        	1.8.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.7.1        	1.7.1      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.7.0        	1.7.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.6.0        	1.6.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.5.0        	1.5.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.4.1        	1.4.1      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.4.0        	1.4.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.3.1        	1.3.1      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator     	1.3.0        	1.3.0      	A Helm chart for deploying the Elastic Cloud on...
elastic/eck-operator-crds	2.14.0       	2.14.0     	ECK operator Custom Resource Definitions
elastic/eck-operator-crds	2.13.0       	2.13.0     	ECK operator Custom Resource Definitions
elastic/eck-operator-crds	2.12.1       	2.12.1     	ECK operator Custom Resource Definitions
elastic/eck-operator-crds	2.12.0       	2.12.0     	ECK operator Custom Resource Definitions
elastic/eck-operator-crds	2.11.1       	2.11.1     	ECK operator Custom Resource Definitions
elastic/eck-operator-crds	2.11.0       	2.11.0     	ECK operator Custom Resource Definitions
elastic/eck-operator-crds	2.10.0       	2.10.0     	ECK operator Custom Resource Definitions
elastic/eck-operator-crds	2.9.0        	2.9.0      	ECK operator Custom Resource Definitions
elastic/eck-operator-crds	2.8.0        	2.8.0      	ECK operator Custom Resource Definitions
elastic/eck-operator-crds	2.7.0        	2.7.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	2.6.1        	2.6.1      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	2.6.0        	2.6.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	2.5.0        	2.5.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	2.4.0        	2.4.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	2.3.0        	2.3.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	2.2.0        	2.2.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	2.1.0        	2.1.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	2.0.0        	2.0.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.9.1        	1.9.1      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.9.0        	1.9.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.8.0        	1.8.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.7.1        	1.7.1      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.7.0        	1.7.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.6.0        	1.6.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.5.0        	1.5.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.4.1        	1.4.1      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.4.0        	1.4.0      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.3.1        	1.3.1      	A Helm chart for installing the ECK operator Cu...
elastic/eck-operator-crds	1.3.0        	1.3.0      	A Helm chart for installing the ECK operator Cu...
bharathkumardasaraju@install-local-k8s-cluster$