all the similar documents groupes as index

All the logs that are generated by our web-app will be stored in an
index called as "web_app_logs"

Lets say we another app called login_app, so the all the logs generated by login application gets stored in the
index called as "login_app_logs"



